config/routes.rb
Rails.application.routes.draw do
  resources :albums
  root "albums#index"
  get "albums/:id", to: "albums#show"
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    validates :Title,presence: true
    validates :Description,presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def index
        @albums = Album.all
    end
    def show
       @albums = Album.find(params[:id])
    end
    def new
        @album = Album.new
    end
    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to root_path
        else
            render :new
        end
    end
    def edit 
    @album = Album.find(params[:id])
    end
    def update
      @album = Album.find(params[:id])
      if @album.update(album_params)
        redirect_to root_path
      else
        render :edit
      end
    end
    def destroy
      @album =Album.find(params[:id])
      if @album.destroy
      redirect_to root_path
      end
    end
          
    private
    def album_params
        params.require(:album).permit(:Title,:Description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crud_controller.rb
class CrudController < ApplicationController
  def index
    @albums = Album.all
  end

  def edit
    debugger
    @albums = Album.new
  end

  def create

    @albums = Album.new(album_params)
    debugger
    if @albums.save
      redirect_to @albums
    else
      render :new
    end
  end
  private
    def album_params
      params.require(:album).permit(:title, :description, :created_date)
    end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crud_helper.rb
module CrudHelper
end

app/views/albums/_form.html.erb
<div id="form">
<%= form_with model: album do |form| %>
    <div>
      <%= form.label :Title %><br>
      <%= form.text_field :Title %>
      <% @album.errors.full_messages_for(:Title).each do|message| %>
        <div>
          <%= message %>
        </div>
       <% end %>
    </div>
    <br>
    <div>
      <%= form.label :Description %><br>
      <%= form.text_area :Description %><br>
      <% @album.errors.full_messages_for(:Description).each do|message| %>
        <div>
          <%= message %>
        </div>
        <% end %>
    
    </div>
  <br>
    <div>
      <%= form.submit :class => 'submit'%>
    </div>
  <% end %>
  </div>

app/views/albums/edit.html.erb
<h1>Edit Form</h1>

<%= render "form", album: @album %>

app/views/albums/index.html.erb
<h1>All RECORDS</h1>
<div id="table">
    <table border="1">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Created_date</th>
            <th>Edit</th>
            <th>Delete</th>
            <th>Show</th>
        </tr>
    <thead>
    <% @albums.each do |album| %>
    <tr>
    <td>
    <%= album.Title %>
    </td>
        <td> <%= album.Description %></td>
        <td> <%= album.created_at %></td>
        <td id="edit"> <%= link_to "Edit", edit_album_path(album) %> 
        </td>
        <td id="delete">
        <%= link_to "Delete", album_path(album), method: :delete%> 
        </td>
        <td id="show">
        <%= link_to "show", album_path(album)%> 
        </td>
    </tr>
    <% end %>
    </table>

    <div id="new">
    <%= link_to "Add New Album", new_album_path %> <br>
    </div>
</div>

app/views/albums/new.html.erb
<h1>New Album</h1>
<div id="form">
<%= form_with model: @album do |form| %>
  <div>
    <%= form.label :Title %><br>
    <%= form.text_field :Title %>
      <% @album.errors.full_messages_for(:Title).each do|message| %>
        <div>
          <%= message %>
        </div>
       <% end %>
  </div>
<br>
  <div>
    <%= form.label :Description %><br>
    <%= form.text_area :Description %>
    <% @album.errors.full_messages_for(:Description).each do|message| %>
      <div>
        <%= message %>
      </div>
      <% end %>
  </div>
   <br>
  <div>
    <%= form.submit :class => 'submit'  %>
  </div>
<% end %>
</div>

app/views/albums/show.html.erb
<h1>New Record Created</h1>
<table border="1">
<thead>
    <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Created_date</th>
    </tr>
<thead>
    <tr>
        <td>
          <%= @albums.Title %>
        </td>
        <td> 
          <%= @albums.Description %>
        </td>
        <td> 
          <%= @albums.created_at %>
      
    </tr>
   
</table>

app/views/crud/edit.html.erb
<h1>Form</h1>
<%=form_with model: @album do |form| %>
    <div>
      <%= form.label :Title %><br>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.label :Description %><br>
      <%= form.text_area :Description %>
    </div>
  <br>
    <div>
      <%= form.submit %><br>
    </div>
  <% end %>
  

app/views/crud/index.html.erb
<table border="1">
<thead>
   <th>Title</th>
   <th>Description</th>
   <th>Created_date</th>
   <th>Actions</th>
 </thead>

 <%= @albums.each do |album| %>
 <tr>
    <td>
     <%= album.title %> 
    </td>
    <td>
     <%= album.description %> 
   </td>
    <td>
     <%= album.created_date %> 
  </td>
 </tr>
 <% end %>

 </table>

app/views/crud/show.html.erb
<table border="1">
<thead>
   <th>Title</th>
   <th>Description</th>
   <th>Created_date</th>
   <th>Actions</th>
 </thead>

 <%= @albums.each do |album| %>
 <tr>
    <td>
     <%= album.title %> 
    </td>
    <td>
     <%= album.description %> 
   </td>
    <td>
     <%= album.created_date %> 
  </td>
 </tr>
 <% end %>

 </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MYAPP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style.css' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>